repos:
  - repo: local
    hooks:
      - id: vala-lint
        name: Vala Lint
        entry: vala-lint
        language: system
        files: \.(vala|vapi|vala.in)$
        args: ["--config=vala-lint.conf"]
        require_serial: true

