name: Build

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'COPYING'
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - 'COPYING'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-build:
    name: Test Build (${{ matrix.profile }})
    runs-on: als-huge
    timeout-minutes: 30

    strategy:
      matrix:
        profile: [default, development]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y meson vala blueprint-compiler \
          'pkgconfig(libadwaita-1)' \
          'pkgconfig(libosinfo-1.0)' \
          'pkgconfig(gee-0.8)' \
          'pkgconfig(udisks2)' \
          'pkgconfig(libsoup-3.0)' \
          gettext-tools

      - name: Setup
        run: meson setup _build -Dprefix=/usr -Dprofile=${{ matrix.profile }}

      - name: Build
        run: ninja install -C _build

      - name: Test
        run: meson test -C _build
